-- Kenchi UI Library
-- Generated by NexusUI Builder

local Kenchi = {}

-- Services
local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")

-- Configuration
local Config = {
    Name = "Kenchi",
    AccentColor = Color3.fromHex("#000000"),
    WindowSize = UDim2.new(0, 500, 0, 400),
    Theme = "dark"
}

-- Create ScreenGui
local function CreateScreenGui()
    local ScreenGui = Instance.new("ScreenGui")
    ScreenGui.Name = Config.Name
    ScreenGui.ResetOnSpawn = false
    ScreenGui.ZIndexMode = "Sibling"
    ScreenGui.Parent = Players.LocalPlayer:WaitForChild("PlayerGui")
    return ScreenGui
end

-- Create Main Window
function Kenchi.CreateWindow(Options)
    Options = Options or {}
    local Window = {}
    
    local ScreenGui = CreateScreenGui()
    local MainFrame = Instance.new("Frame")
    local UICorner = Instance.new("UICorner")
    
    MainFrame.Name = "MainFrame"
    MainFrame.Size = Options.Size or Config.WindowSize
    MainFrame.Position = UDim2.new(0.5, -(tonumber(Config.WindowSize.X.Offset) / 2), 0.5, -(tonumber(Config.WindowSize.Y.Offset) / 2))
    MainFrame.BackgroundColor3 = Color3.fromHex("#14141f")
    MainFrame.BorderSizePixel = 0
    MainFrame.Parent = ScreenGui
    
    UICorner.CornerRadius = UDim.new(0, 12)
    UICorner.Parent = MainFrame
    
    -- Make draggable
    local dragging = false
    local dragStart, startPos
    
    MainFrame.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = true
            dragStart = input.Position
            startPos = MainFrame.Position
        end
    end)
    
    return Window
end

-- Add Tab
function Window.AddTab(Name)
    local Tab = {}
    Tab.Name = Name
    Tab.Components = {}
    
    -- Tab implementation
    
    return Tab
end

-- Add Button Component
function Tab.AddButton(Options)
    Options = Options or {}
    local Button = Instance.new("TextButton")
    
    Button.Name = Options.Name or "Button"
    Button.Text = Options.Name or "Click Me"
    Button.Size = UDim2.new(0, 200, 0, 40)
    Button.BackgroundColor3 = Config.AccentColor
    Button.TextColor3 = Color3.fromHex("#0a0a0f")
    Button.Font = Enum.Font.GothamBold
    Button.TextSize = 14
    
    Button.MouseButton1Click:Connect(function()
        if Options.Callback then
            Options.Callback()
        end
    end)
    
    return Button
end

-- Add Toggle Component
function Tab.AddToggle(Options)
    Options = Options or {}
    local Toggle = {
        Value = Options.Default or false
    }
    
    -- Toggle implementation
    
    return Toggle
end

-- Add Slider Component
function Tab.AddSlider(Options)
    Options = Options or {}
    local Slider = {
        Value = Options.Default or 50,
        Min = Options.Min or 0,
        Max = Options.Max or 100
    }
    
    -- Slider implementation
    
    return Slider
end

-- Add Dropdown Component
function Tab.AddDropdown(Options)
    Options = Options or {}
    local Dropdown = {
        Options = Options.Options or {},
        Selected = nil
    }
    
    -- Dropdown implementation
    
    return Dropdown
end

return Kenchis