"syntax-comment">"syntax-comment">--[[
    NexusUI - Roblox UI Library
    Generated by NexusUI Builder
    Version: 3.0
]]

local NexusUI = {}

"syntax-comment">-- Services
local Players = game:GetService("Players")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")

"syntax-comment">-- Configuration
local Config = {
    Name = "NexusUI",
    Version = "3.0",
    AccentColor = Color3.fromHex("#00e5a0"),
    Theme = "dark",
    WindowSize = Vector2.new(520, 500),
    Draggable = true,
    Minimizable = true,
    SaveSettings = false
}

"syntax-comment">-- Theme Colors
local Theme = {
    Background = Color3.fromHex("#0f0f14"),
    Card = Color3.fromHex("#16161e"),
    Border = Color3.fromHex("#222230"),
    Accent = Color3.fromHex("#00e5a0"),
    Text = Color3.fromHex("#e4e4e9"),
    TextMuted = Color3.fromHex("#6e6e7a")
}

"syntax-comment">-- Utility Functions
local function Create(instance, properties)
    local obj = Instance.new(instance)
    for prop, value in pairs(properties) do
        obj[prop] = value
    end
    return obj
end

local function Tween(obj, properties, duration, easingStyle, easingDirection)
    duration = duration or 0.3
    easingStyle = easingStyle or Enum.EasingStyle.Quart
    easingDirection = easingDirection or Enum.EasingDirection.Out
    local tween = TweenService:Create(obj, TweenInfo.new(duration, easingStyle, easingDirection), properties)
    tween:Play()
    return tween
end

local function Round(number, decimalPlaces)
    decimalPlaces = decimalPlaces or 0
    return tonumber(string.format("%." .. decimalPlaces .. "f", number))
end

"syntax-comment">-- Create Window
function NexusUI:CreateWindow(options)
    options = options or {}
    
    local Window = {}
    Window.Name = options.Name or Config.Name
    Window.Size = options.Size or UDim2.new(0, Config.WindowSize.X, 0, Config.WindowSize.Y)
    Window.Tabs = {}
    Window.CurrentTab = nil
    Window.IsMinimized = false
    Window.ScreenGui = nil
    Window.MainFrame = nil
    
    "syntax-comment">-- Create ScreenGui
    local ScreenGui = Create("ScreenGui", {
        Name = Window.Name,
        ResetOnSpawn = false,
        ZIndexMode = "Sibling",
        IgnoreGuiInset = true
    })
    
    if Players.LocalPlayer:FindFirstChild("PlayerGui") then
        ScreenGui.Parent = Players.LocalPlayer.PlayerGui
    else
        ScreenGui.Parent = game:GetService("CoreGui")
    end
    
    Window.ScreenGui = ScreenGui
    
    "syntax-comment">-- Create Main Frame
    local MainFrame = Create("Frame", {
        Name = "MainFrame",
        Size = Window.Size,
        Position = UDim2.new(0.5, -Config.WindowSize.X / 2, 0.5, -Config.WindowSize.Y / 2),
        BackgroundColor3 = Theme.Background,
        BorderSizePixel = 0,
        Parent = ScreenGui
    })
    
    local MainCorner = Create("UICorner", {
        CornerRadius = UDim.new(0, 12),
        Parent = MainFrame
    })
    
    Window.MainFrame = MainFrame
    
    "syntax-comment">-- Create Title Bar
    local TitleBar = Create("Frame", {
        Name = "TitleBar",
        Size = UDim2.new(1, 0, 0, 44),
        BackgroundColor3 = Theme.Card,
        BorderSizePixel = 0,
        Parent = MainFrame
    })
    
    local TitleBarCorner = Create("UICorner", {
        CornerRadius = UDim.new(0, 12),
        Parent = TitleBar
    })
    
    "syntax-comment">-- Fix corner overlap
    local TitleBarFix = Create("Frame", {
        Size = UDim2.new(1, 0, 0, 20),
        Position = UDim2.new(0, 0, 1, -20),
        BackgroundColor3 = Theme.Card,
        BorderSizePixel = 0,
        Parent = TitleBar
    })
    
    local TitleLabel = Create("TextLabel", {
        Name = "Title",
        Size = UDim2.new(1, -100, 1, 0),
        Position = UDim2.new(0, 16, 0, 0),
        BackgroundTransparency = 1,
        Text = Window.Name,
        TextColor3 = Theme.Text,
        TextSize = 15,
        Font = Enum.Font.GothamBold,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = TitleBar
    })
    
    Window.TitleBar = TitleBar
    
    "syntax-comment">-- Minimize Button (if enabled)
    if Config.Minimizable then
        local MinimizeBtn = Create("TextButton", {
            Name = "MinimizeBtn",
            Size = UDim2.new(0, 32, 0, 28),
            Position = UDim2.new(1, -40, 0.5, -14),
            BackgroundColor3 = Theme.Accent,
            BorderSizePixel = 0,
            Text = "-",
            TextColor3 = Theme.Background,
            TextSize = 18,
            Font = Enum.Font.GothamBold,
            Parent = TitleBar
        })
        
        local MinimizeCorner = Create("UICorner", {
            CornerRadius = UDim.new(0, 6),
            Parent = MinimizeBtn
        })
        
        MinimizeBtn.MouseButton1Click:Connect(function()
            Window:ToggleMinimize()
        end)
        
        Window.MinimizeBtn = MinimizeBtn
    end
    
    "syntax-comment">-- Sidebar Container
    local Sidebar = Create("Frame", {
        Name = "Sidebar",
        Size = UDim2.new(0, 140, 1, -44),
        Position = UDim2.new(0, 0, 0, 44),
        BackgroundColor3 = Theme.Card,
        BorderSizePixel = 0,
        Parent = MainFrame
    })
    
    local SidebarLayout = Create("UIListLayout", {
        Padding = UDim.new(0, 4),
        Parent = Sidebar
    })
    
    local SidebarPadding = Create("UIPadding", {
        PaddingTop = UDim.new(0, 12),
        PaddingLeft = UDim.new(0, 12),
        PaddingRight = UDim.new(0, 12),
        Parent = Sidebar
    })
    
    Window.Sidebar = Sidebar
    Window.SidebarLayout = SidebarLayout
    
    "syntax-comment">-- Content Container
    local Content = Create("ScrollingFrame", {
        Name = "Content",
        Size = UDim2.new(1, -140, 1, -56),
        Position = UDim2.new(0, 148, 0, 52),
        BackgroundTransparency = 1,
        BorderSizePixel = 0,
        ScrollBarThickness = 4,
        ScrollBarImageColor3 = Theme.Accent,
        CanvasSize = UDim2.new(0, 0, 0, 0),
        Parent = MainFrame
    })
    
    local ContentLayout = Create("UIListLayout", {
        Padding = UDim.new(0, 8),
        Parent = Content
    })
    
    ContentLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
        Content.CanvasSize = UDim2.new(0, 0, 0, ContentLayout.AbsoluteContentSize.Y + 20)
    end)
    
    Window.Content = Content
    Window.ContentLayout = ContentLayout
    
    "syntax-comment">-- Draggable Logic
    if Config.Draggable then
        local dragging = false
        local dragStart, startPos
        
        TitleBar.InputBegan:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
                dragging = true
                dragStart = input.Position
                startPos = MainFrame.Position
            end
        end)
        
        UserInputService.InputChanged:Connect(function(input)
            if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then
                local delta = input.Position - dragStart
                MainFrame.Position = UDim2.new(
                    startPos.X.Scale, startPos.X.Offset + delta.X,
                    startPos.Y.Scale, startPos.Y.Offset + delta.Y
                )
            end
        end)
        
        UserInputService.InputEnded:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
                dragging = false
            end
        end)
    end
    
    "syntax-comment">-- Window Methods
    function Window:AddTab(name, icon)
        local Tab = {}
        Tab.Name = name
        Tab.Icon = icon
        Tab.Window = Window
        Tab.Components = {}
        
        "syntax-comment">-- Create Tab Button
        local TabBtn = Create("TextButton", {
            Name = name .. "Tab",
            Size = UDim2.new(1, 0, 0, 36),
            BackgroundColor3 = Theme.Background,
            BorderSizePixel = 0,
            Text = "",
            TextTransparency = 1,
            Parent = self.Sidebar
        })
        
        local TabBtnCorner = Create("UICorner", {
            CornerRadius = UDim.new(0, 8),
            Parent = TabBtn
        })
        
        local TabBtnLabel = Create("TextLabel", {
            Size = UDim2.new(1, 0, 1, 0),
            BackgroundTransparency = 1,
            Text = name,
            TextColor3 = Theme.TextMuted,
            TextSize = 13,
            Font = Enum.Font.GothamMedium,
            Parent = TabBtn
        })
        
        "syntax-comment">-- Create Tab Content Frame
        local TabContent = Create("Frame", {
            Name = name .. "Content",
            Size = UDim2.new(1, 0, 0, 0),
            BackgroundTransparency = 1,
            BorderSizePixel = 0,
            Visible = false,
            Parent = self.Content
        })
        
        local TabContentLayout = Create("UIListLayout", {
            Padding = UDim.new(0, 8),
            Parent = TabContent
        })
        
        TabContentLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
            TabContent.Size = UDim2.new(1, 0, 0, TabContentLayout.AbsoluteContentSize.Y)
        end)
        
        Tab.ContentFrame = TabContent
        Tab.ContentLayout = TabContentLayout
        
        "syntax-comment">-- Tab Button Click
        TabBtn.MouseButton1Click:Connect(function()
            self:SelectTab(Tab)
        end)
        
        Tab.Button = TabBtn
        Tab.Label = TabBtnLabel
        
        table.insert(self.Tabs, Tab)
        
        "syntax-comment">-- Auto-select first tab
        if #self.Tabs == 1 then
            self:SelectTab(Tab)
        end
        
        "syntax-comment">-- Tab Component Methods
        function Tab:AddSection(title)
            local Section = {}
            Section.Name = title
            Section.Tab = Tab
            
            local SectionFrame = Create("Frame", {
                Name = title .. "Section",
                Size = UDim2.new(1, 0, 0, 0),
                AutomaticSize = Enum.AutomaticSize.Y,
                BackgroundColor3 = Theme.Card,
                BorderSizePixel = 0,
                Parent = self.ContentFrame
            })
            
            local SectionCorner = Create("UICorner", {
                CornerRadius = UDim.new(0, 8),
                Parent = SectionFrame
            })
            
            local SectionStroke = Create("UIStroke", {
                Color = Theme.Border,
                Thickness = 1,
                Parent = SectionFrame
            })
            
            local SectionPadding = Create("UIPadding", {
                PaddingTop = UDim.new(0, 16),
                PaddingBottom = UDim.new(0, 16),
                PaddingLeft = UDim.new(0, 16),
                PaddingRight = UDim.new(0, 16),
                Parent = SectionFrame
            })
            
            local SectionTitle = Create("TextLabel", {
                Size = UDim2.new(1, 0, 0, 20),
                BackgroundTransparency = 1,
                Text = title,
                TextColor3 = Theme.Text,
                TextSize = 14,
                Font = Enum.Font.GothamBold,
                TextXAlignment = Enum.TextXAlignment.Left,
                Parent = SectionFrame
            })
            
            local SectionContent = Create("Frame", {
                Name = "Content",
                Size = UDim2.new(1, 0, 0, 0),
                AutomaticSize = Enum.AutomaticSize.Y,
                BackgroundTransparency = 1,
                Parent = SectionFrame
            })
            
            local SectionContentLayout = Create("UIListLayout", {
                Padding = UDim.new(0, 10),
                Parent = SectionContent
            })
            
            Section.Frame = SectionFrame
            Section.Content = SectionContent
            Section.Layout = SectionContentLayout
            
            "syntax-comment">-- Section Component Methods
            function Section:AddButton(options)
                options = options or {}
                
                local Button = {}
                Button.Name = options.Name or "Button"
                Button.Callback = options.Callback or function() end
                
                local Btn = Create("TextButton", {
                    Name = Button.Name,
                    Size = UDim2.new(1, 0, 0, 40),
                    BackgroundColor3 = Theme.Accent,
                    BorderSizePixel = 0,
                    Text = Button.Name,
                    TextColor3 = Theme.Background,
                    TextSize = 13,
                    Font = Enum.Font.GothamBold,
                    Parent = self.Content
                })
                
                local BtnCorner = Create("UICorner", {
                    CornerRadius = UDim.new(0, 8),
                    Parent = Btn
                })
                
                Btn.MouseButton1Click:Connect(function()
                    Button.Callback()
                end)
                
                Button.Instance = Btn
                
                return Button
            end
            
            function Section:AddToggle(options)
                options = options or {}
                
                local Toggle = {}
                Toggle.Name = options.Name or "Toggle"
                Toggle.Default = options.Default or false
                Toggle.Callback = options.Callback or function() end
                Toggle.Value = Toggle.Default
                
                local ToggleFrame = Create("Frame", {
                    Name = Toggle.Name,
                    Size = UDim2.new(1, 0, 0, 36),
                    BackgroundTransparency = 1,
                    Parent = self.Content
                })
                
                local ToggleLabel = Create("TextLabel", {
                    Size = UDim2.new(1, -60, 1, 0),
                    BackgroundTransparency = 1,
                    Text = Toggle.Name,
                    TextColor3 = Theme.Text,
                    TextSize = 13,
                    Font = Enum.Font.GothamMedium,
                    TextXAlignment = Enum.TextXAlignment.Left,
                    Parent = ToggleFrame
                })
                
                local ToggleBtn = Create("TextButton", {
                    Size = UDim2.new(0, 44, 0, 24),
                    Position = UDim2.new(1, -44, 0.5, -12),
                    BackgroundColor3 = Toggle.Default and Theme.Accent or Theme.Background,
                    BorderSizePixel = 0,
                    Text = "",
                    Parent = ToggleFrame
                })
                
                local ToggleCorner = Create("UICorner", {
                    CornerRadius = UDim.new(0, 12),
                    Parent = ToggleBtn
                })
                
                local ToggleStroke = Create("UIStroke", {
                    Color = Toggle.Default and Theme.Accent or Theme.Border,
                    Thickness = 1,
                    Parent = ToggleBtn
                })
                
                local ToggleCircle = Create("Frame", {
                    Size = UDim2.new(0, 18, 0, 18),
                    Position = Toggle.Default and UDim2.new(1, -21, 0.5, -9) or UDim2.new(0, 3, 0.5, -9),
                    BackgroundColor3 = Theme.Text,
                    BorderSizePixel = 0,
                    Parent = ToggleBtn
                })
                
                local ToggleCircleCorner = Create("UICorner", {
                    CornerRadius = UDim.new(0, 9),
                    Parent = ToggleCircle
                })
                
                ToggleBtn.MouseButton1Click:Connect(function()
                    Toggle.Value = not Toggle.Value
                    
                    Tween(ToggleCircle, {
                        Position = Toggle.Value and UDim2.new(1, -21, 0.5, -9) or UDim2.new(0, 3, 0.5, -9)
                    }, 0.2)
                    
                    Tween(ToggleBtn, {
                        BackgroundColor3 = Toggle.Value and Theme.Accent or Theme.Background
                    }, 0.2)
                    
                    ToggleStroke.Color = Toggle.Value and Theme.Accent or Theme.Border
                    
                    Toggle.Callback(Toggle.Value)
                end)
                
                Toggle.Instance = ToggleFrame
                Toggle.Button = ToggleBtn
                
                return Toggle
            end
            
            function Section:AddSlider(options)
                options = options or {}
                
                local Slider = {}
                Slider.Name = options.Name or "Slider"
                Slider.Min = options.Min or 0
                Slider.Max = options.Max or 100
                Slider.Default = options.Default or 50
                Slider.Callback = options.Callback or function() end
                Slider.Value = Slider.Default
                
                local SliderFrame = Create("Frame", {
                    Name = Slider.Name,
                    Size = UDim2.new(1, 0, 0, 50),
                    BackgroundTransparency = 1,
                    Parent = self.Content
                })
                
                local SliderHeader = Create("Frame", {
                    Size = UDim2.new(1, 0, 0, 20),
                    BackgroundTransparency = 1,
                    Parent = SliderFrame
                })
                
                local SliderLabel = Create("TextLabel", {
                    Size = UDim2.new(1, -50, 1, 0),
                    BackgroundTransparency = 1,
                    Text = Slider.Name,
                    TextColor3 = Theme.Text,
                    TextSize = 13,
                    Font = Enum.Font.GothamMedium,
                    TextXAlignment = Enum.TextXAlignment.Left,
                    Parent = SliderHeader
                })
                
                local SliderValue = Create("TextLabel", {
                    Size = UDim2.new(0, 40, 1, 0),
                    Position = UDim2.new(1, -40, 0, 0),
                    BackgroundTransparency = 1,
                    Text = tostring(Slider.Default),
                    TextColor3 = Theme.Accent,
                    TextSize = 13,
                    Font = Enum.Font.GothamBold,
                    Parent = SliderHeader
                })
                
                local SliderTrack = Create("Frame", {
                    Size = UDim2.new(1, 0, 0, 6),
                    Position = UDim2.new(0, 0, 1, -6),
                    BackgroundColor3 = Theme.Background,
                    BorderSizePixel = 0,
                    Parent = SliderFrame
                })
                
                local SliderTrackCorner = Create("UICorner", {
                    CornerRadius = UDim.new(0, 3),
                    Parent = SliderTrack
                })
                
                local SliderFill = Create("Frame", {
                    Size = UDim2.new((Slider.Default - Slider.Min) / (Slider.Max - Slider.Min), 0, 1, 0),
                    BackgroundColor3 = Theme.Accent,
                    BorderSizePixel = 0,
                    Parent = SliderTrack
                })
                
                local SliderFillCorner = Create("UICorner", {
                    CornerRadius = UDim.new(0, 3),
                    Parent = SliderFill
                })
                
                local SliderInput = Create("TextButton", {
                    Size = UDim2.new(1, 0, 1, 0),
                    BackgroundTransparency = 1,
                    Text = "",
                    Parent = SliderTrack
                })
                
                local function UpdateSlider(input)
                    local x = math.clamp(input.Position.X, 0, SliderTrack.AbsoluteSize.X)
                    local percent = x / SliderTrack.AbsoluteSize.X
                    local value = Round(Slider.Min + (Slider.Max - Slider.Min) * percent)
                    
                    Slider.Value = value
                    SliderValue.Text = tostring(value)
                    SliderFill.Size = UDim2.new(percent, 0, 1, 0)
                    Slider.Callback(value)
                end
                
                SliderInput.InputBegan:Connect(function(input)
                    if input.UserInputType == Enum.UserInputType.MouseButton1 then
                        UpdateSlider(input)
                    end
                end)
                
                SliderInput.InputChanged:Connect(function(input)
                    if input.UserInputType == Enum.UserInputType.MouseMovement then
                        if UserInputService:IsMouseButtonPressed(Enum.UserInputType.MouseButton1) then
                            UpdateSlider(input)
                        end
                    end
                end)
                
                Slider.Instance = SliderFrame
                Slider.Track = SliderTrack
                Slider.Fill = SliderFill
                
                return Slider
            end
            
            function Section:AddDropdown(options)
                options = options or {}
                
                local Dropdown = {}
                Dropdown.Name = options.Name or "Dropdown"
                Dropdown.Options = options.Options or {}
                Dropdown.Default = options.Default or (Dropdown.Options[1] or "Select...")
                Dropdown.Callback = options.Callback or function() end
                Dropdown.Value = Dropdown.Default
                Dropdown.Open = false
                
                local DropdownFrame = Create("Frame", {
                    Name = Dropdown.Name,
                    Size = UDim2.new(1, 0, 0, 36),
                    BackgroundTransparency = 1,
                    Parent = self.Content
                })
                
                local DropdownLabel = Create("TextLabel", {
                    Size = UDim2.new(0, 100, 1, 0),
                    BackgroundTransparency = 1,
                    Text = Dropdown.Name,
                    TextColor3 = Theme.Text,
                    TextSize = 13,
                    Font = Enum.Font.GothamMedium,
                    TextXAlignment = Enum.TextXAlignment.Left,
                    Parent = DropdownFrame
                })
                
                local DropdownBtn = Create("TextButton", {
                    Size = UDim2.new(0, 160, 1, 0),
                    Position = UDim2.new(1, -160, 0, 0),
                    BackgroundColor3 = Theme.Background,
                    BorderSizePixel = 0,
                    Text = Dropdown.Default,
                    TextColor3 = Theme.Text,
                    TextSize = 12,
                    Font = Enum.Font.GothamMedium,
                    Parent = DropdownFrame
                })
                
                local DropdownBtnCorner = Create("UICorner", {
                    CornerRadius = UDim.new(0, 6),
                    Parent = DropdownBtn
                })
                
                local DropdownBtnStroke = Create("UIStroke", {
                    Color = Theme.Border,
                    Thickness = 1,
                    Parent = DropdownBtn
                })
                
                local DropdownArrow = Create("TextLabel", {
                    Size = UDim2.new(0, 20, 1, 0),
                    Position = UDim2.new(1, -26, 0, 0),
                    BackgroundTransparency = 1,
                    Text = "▼",
                    TextColor3 = Theme.TextMuted,
                    TextSize = 8,
                    Parent = DropdownBtn
                })
                
                local DropdownList = Create("Frame", {
                    Size = UDim2.new(1, 0, 0, 0),
                    Position = UDim2.new(0, 0, 1, 4),
                    BackgroundColor3 = Theme.Card,
                    BorderSizePixel = 0,
                    Visible = false,
                    ClipsDescendants = true,
                    Parent = DropdownBtn
                })
                
                local DropdownListCorner = Create("UICorner", {
                    CornerRadius = UDim.new(0, 6),
                    Parent = DropdownList
                })
                
                local DropdownListStroke = Create("UIStroke", {
                    Color = Theme.Border,
                    Thickness = 1,
                    Parent = DropdownList
                })
                
                local DropdownListLayout = Create("UIListLayout", {
                    Parent = DropdownList
                })
                
                local function RefreshOptions()
                    for _, child in pairs(DropdownList:GetChildren()) do
                        if child:IsA("TextButton") then
                            child:Destroy()
                        end
                    end
                    
                    for _, option in pairs(Dropdown.Options) do
                        local OptionBtn = Create("TextButton", {
                            Size = UDim2.new(1, 0, 0, 32),
                            BackgroundTransparency = 1,
                            Text = option,
                            TextColor3 = Dropdown.Value == option and Theme.Accent or Theme.Text,
                            TextSize = 12,
                            Font = Dropdown.Value == option and Enum.Font.GothamBold or Enum.Font.GothamMedium,
                            Parent = DropdownList
                        })
                        
                        OptionBtn.MouseButton1Click:Connect(function()
                            Dropdown.Value = option
                            DropdownBtn.Text = option
                            Dropdown.Callback(option)
                            Dropdown:Toggle()
                            RefreshOptions()
                        end)
                    end
                    
                    DropdownList.Size = UDim2.new(1, 0, 0, #Dropdown.Options * 32)
                end
                
                function Dropdown:Toggle()
                    Dropdown.Open = not Dropdown.Open
                    DropdownList.Visible = Dropdown.Open
                    DropdownArrow.Text = Dropdown.Open and "▲" or "▼"
                end
                
                DropdownBtn.MouseButton1Click:Connect(function()
                    Dropdown:Toggle()
                end)
                
                RefreshOptions()
                
                Dropdown.Instance = DropdownFrame
                Dropdown.List = DropdownList
                
                return Dropdown
            end
            
            function Section:AddTextbox(options)
                options = options or {}
                
                local Textbox = {}
                Textbox.Name = options.Name or "Textbox"
                Textbox.Default = options.Default or ""
                Textbox.Placeholder = options.Placeholder or "Enter text..."
                Textbox.Callback = options.Callback or function() end
                Textbox.Value = Textbox.Default
                
                local TextboxFrame = Create("Frame", {
                    Name = Textbox.Name,
                    Size = UDim2.new(1, 0, 0, 36),
                    BackgroundTransparency = 1,
                    Parent = self.Content
                })
                
                local TextboxLabel = Create("TextLabel", {
                    Size = UDim2.new(0, 100, 1, 0),
                    BackgroundTransparency = 1,
                    Text = Textbox.Name,
                    TextColor3 = Theme.Text,
                    TextSize = 13,
                    Font = Enum.Font.GothamMedium,
                    TextXAlignment = Enum.TextXAlignment.Left,
                    Parent = TextboxFrame
                })
                
                local TextboxInput = Create("TextBox", {
                    Size = UDim2.new(0, 160, 1, 0),
                    Position = UDim2.new(1, -160, 0, 0),
                    BackgroundColor3 = Theme.Background,
                    BorderSizePixel = 0,
                    Text = Textbox.Default,
                    PlaceholderText = Textbox.Placeholder,
                    TextColor3 = Theme.Text,
                    PlaceholderColor3 = Theme.TextMuted,
                    TextSize = 12,
                    Font = Enum.Font.GothamMedium,
                    ClearTextOnFocus = false,
                    Parent = TextboxFrame
                })
                
                local TextboxCorner = Create("UICorner", {
                    CornerRadius = UDim.new(0, 6),
                    Parent = TextboxInput
                })
                
                local TextboxStroke = Create("UIStroke", {
                    Color = Theme.Border,
                    Thickness = 1,
                    Parent = TextboxInput
                })
                
                TextboxInput.Focused:Connect(function()
                    TextboxStroke.Color = Theme.Accent
                end)
                
                TextboxInput.FocusLost:Connect(function()
                    TextboxStroke.Color = Theme.Border
                    Textbox.Value = TextboxInput.Text
                    Textbox.Callback(TextboxInput.Text)
                end)
                
                Textbox.Instance = TextboxFrame
                Textbox.Input = TextboxInput
                
                return Textbox
            end
            
            return Section
        end
        
        return Tab
    end
    
    function Window:SelectTab(tab)
        "syntax-comment">-- Hide all tabs
        for _, t in pairs(self.Tabs) do
            t.ContentFrame.Visible = false
            t.Label.TextColor3 = Theme.TextMuted
        end
        
        "syntax-comment">-- Show selected tab
        tab.ContentFrame.Visible = true
        tab.Label.TextColor3 = Theme.Accent
        self.CurrentTab = tab
    end
    
    function Window:ToggleMinimize()
        self.IsMinimized = not self.IsMinimized
        
        if self.IsMinimized then
            Tween(self.MainFrame, {
                Size = UDim2.new(0, Config.WindowSize.X, 0, 44)
            }, 0.3)
            
            self.Sidebar.Visible = false
            self.Content.Visible = false
        else
            Tween(self.MainFrame, {
                Size = self.Size
            }, 0.3)
            
            self.Sidebar.Visible = true
            self.Content.Visible = true
        end
    end
    
    function Window:Destroy()
        self.ScreenGui:Destroy()
    end
    
    return Window
end

return NexusUI